### ISSUE TITLE
need cars

### ISSUE THREAD

**Issue by iasatan** [iasatan/uniWebtech1#2]
write a car json object

**Comment by iasatan** [comment]
{
        "name": "Corolla",
        "consumption": "7l/100km",
        "color": "gray",
        "manufacturer": "Toyota",
        "available": 1,
        "year": 2003,
        "horsepower":100
    }
Should look like this, and should be real data(or at least look like that)

**Comment by valtnagy** [comment]
```
{
    "name": "Saxo",
    "consumption": "4l/100km",
    "color": "blue",
    "manufacturer": "Citroen",
    "available": 2,
    "year": 2001,
    "horsepower":65
}
```

**Comment by AppsByFen** [comment]
Ide kell írni?

{
    "name": "Panda",
    "consumption": "6l/100km",
    "color": "Red",
    "manufacturer": "Fiat",
    "available": 1,
    "year": 2000,
    "horsepower":85
}

**Comment by Scitrix** [comment]
Szeszák Ádám

{
    "name": "Fabia",
    "consumption": "5l/100km",
    "color": "white",
    "manufacturer": "Skoda",
    "available": 15,
    "year": 2007,
    "horsepower":68
}

**Comment by szacskesz** [comment]
Szacsuri Norbert (G0XXTC)
{
    "name": "Laguna II",
    "consumption": "6l/100km",
    "color": "silver",
    "manufacturer": "Renault",
    "available": 1,
    "year": 2003,
    "horsepower": 96
}

**Comment by suleabel** [comment]
Süle Ábel

{
    "name": "Supra",
    "consumption": "13l/100km",
    "color": "red",
    "manufacturer": "Toyota",
    "available": 8,
    "year": 1995,
    "horsepower":340
}

**Comment by tsupack** [comment]
Nussbaumer Alex

{
    "name": "Zafira",
    "consumption": "8l/100km",
    "color": "green",
    "manufacturer": "Opel",
    "available": 1,
    "year": 2002,
    "horsepower":116
}

**Comment by andrassajo** [comment]
Sajó András

{
    "name": "Ibiza",
    "consumption": "6l/100km",
    "color": "blue",
    "manufacturer": "Seat",
    "available": 100,
    "year": 2006,
    "horsepower": 120,
}

**Comment by danxdlul** [comment]
Kása Dániel
{
    "name": "Prelude",
    "consumption": "9l/100km",
    "color": "red",
    "manufacturer": "Honda",
    "available": 11,
    "year": 1999,
    "horsepower":150
}

**Comment by PasztorBence** [comment]
{
    "name": "V40",
    "consumption": "5.6l/100km",
    "color": "Ocean blue",
    "manufacturer": "Volvo",
    "available": 1,
    "year": 2014,
    "horsepower":150
}

**Comment by nyitraibalazs** [comment]
Nyitrai Balázs
{
    "name": "Primera",
    "consumption": "9l/100km",
    "color": "brown",
    "manufacturer": "Nissan",
    "available": 15,
    "year": 2001,
    "horsepower":110
}

**Comment by MMakkai** [comment]
Makkai Márk
{
"name": "Passat",
    "consumption": "6l/100km",
    "color": "black",
    "manufacturer": "Volkswagen",
    "available": 1,
    "year": 2009,
    "horsepower":140
}

**Comment by DorinaFerencsik** [comment]
Ferencsik Dorina
{
    "name": "Lacetti",
    "consumption": "9l/100km",
    "color": "black",
    "manufacturer": "Chevrolet",
    "available": 5,
    "year": 2010,
    "horsepower":109
}

**Comment by aron123** [comment]
Kiss Áron

```json
{
    "name": "P601",
    "consumption": "8l / 100km",
    "color": "lightblue",
    "manufacturer": "Trabant",
    "available": 3,
    "year": 1964,
    "horsepower": 26
}
```

**Comment by MihalyPapp** [comment]
Papp Mihály
{
"name": "Yaris",
"consumption": "5l/100km",
"color": "silver",
"manufacturer": "Toyota",
"available": 1,
"year": 2007,
"horsepower":69
}

**Comment by fehermate** [comment]
Fehér Máté

{
"name": "911 Carrera",
"consumption": "8.3l/100km",
"color": "white",
"manufacturer": "Porsche",
"available": 1,
"year": 2012,
"horsepower":345
}

**Comment by iasatan** [comment]
pls no more, it's annoying.
I have more than enough car, column deleted from attendance
